### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [DynamicGenetics/COVID-19-Community-Response#88]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TWFNK9
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by ninadicara** [comment]
Sorry for not responding to this at the time! We will likely aim to keep all of our code on the GitHub repository with a DOI to here as a lot of the data is going to be updated automatically, and may eventually not all be COVID-19 specific. Thanks for letting us know though, and hopefully since the DOI links out to this repository people can come here for further updates if they need them :-)
